property_types: ['STRING', 'INTEGER', 'DATE']
validators: ['', 'PARTICIPANT_ID']
minimum_android_version_code: 1
exception_notifications:
  email_prefix: '[LSTracker] '
  sender: 'noreply@chpir.org'
  recipients: ['michael@chpir.org', 'leonard@chpir.org']
