property_types: ['STRING', 'INTEGER', 'DATE']
validators: ['', 'PARTICIPANT_ID', 'CENTER_ID', 'CHILD_ID', 'CAREGIVER_ID']
minimum_android_version_code: 1
exception_notifications:
  email_prefix: '[LSTracker] '
  sender: 'noreply@chpir.org'
  recipients: ['leonard@chpir.org']
danger_zone_days: 3